name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - api: vulkan
            configuration: Release
          - api: vulkan
            configuration: Debug
          - api: d3d12
            configuration: Release
    runs-on: "windows-latest"
    env:
      msbuild_path: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: python -m pip install requests tqdm

      - name: Generate project files
        shell: python
        env:
          API: ${{ matrix.api }}
        run: |
          import subprocess
          import os
          api = os.environ["API"]
          subprocess.run(f"python generate_vs2022_{api}.py")

      - name: Build
        shell: cmd
        run: '"%msbuild_path%\MSBuild.exe" /p:Platform=Windows /p:Configuration=${{ matrix.configuration }} /m spartan.sln'

      - name: Create artifacts
        if: github.event_name != 'pull_request' && matrix.api == 'vulkan'
        shell: cmd
        run: |
          echo "Creating artifacts for ${{ matrix.api }} - ${{ matrix.configuration }}"
          IF "${{ matrix.configuration }}" == "Release" (
            echo "Creating full build archive for Release..."
            build_scripts\7z.exe a -bb1 spartan_vulkan_full.7z .\binaries\dxcompiler.dll .\binaries\fmod.dll .\binaries\data .\binaries\project .\binaries\spartan_${{ matrix.api }}.exe
            echo "Creating binaries-only archive for Release..."
            build_scripts\7z.exe a -bb1 spartan_vulkan_binaries_release.7z .\binaries\dxcompiler.dll .\binaries\fmod.dll .\binaries\data .\binaries\spartan_${{ matrix.api }}.exe
          ) ELSE (
            echo "Creating binaries-only archive for Debug..."
            build_scripts\7z.exe a -bb1 spartan_vulkan_binaries_debug.7z .\binaries\dxcompiler.dll .\binaries\fmodL.dll .\binaries\data .\binaries\spartan_${{ matrix.api }}_debug.exe
          )
          echo "Artifact creation completed for ${{ matrix.api }} - ${{ matrix.configuration }}"

      - name: Upload full artifact
        if: github.event_name != 'pull_request' && matrix.api == 'vulkan' && matrix.configuration == 'Release'
        uses: actions/upload-artifact@v4
        with:
          name: spartan_vulkan_full
          path: spartan_vulkan_full.7z

      - name: Upload binaries-only artifact
        if: github.event_name != 'pull_request' && matrix.api == 'vulkan'
        uses: actions/upload-artifact@v4
        with:
          name: spartan_vulkan_binaries_${{ matrix.configuration == 'Release' && 'release' || 'debug' }}
          path: spartan_vulkan_binaries_${{ matrix.configuration == 'Release' && 'release' || 'debug' }}.7z

  release:
    if: github.event_name != 'pull_request'
    runs-on: "ubuntu-latest"
    needs: build
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
     
      - name: Download vulkan full build (Release)
        uses: actions/download-artifact@v4
        with:
          name: spartan_vulkan_full
          path: spartan_vulkan_full.7z

      - name: Download vulkan binaries-only release build
        uses: actions/download-artifact@v4
        with:
          name: spartan_vulkan_binaries_release
          path: spartan_vulkan_binaries_release.7z

      - name: Download vulkan binaries-only debug build
        uses: actions/download-artifact@v4
        with:
          name: spartan_vulkan_binaries_debug
          path: spartan_vulkan_binaries_debug.7z
      
      - name: Publish release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            spartan_vulkan_full.7z
            spartan_vulkan_binaries_release.7z
            spartan_vulkan_binaries_debug.7z

      - name: Set environment file for release
        run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
