name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        api: [vulkan, d3d12]
    runs-on: "windows-2022"
    env:
      msbuild_path: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\
    steps:
      - uses: actions/checkout@v3

      - name: Generate project files
        shell: python
        env:
          API: ${{ matrix.api }}
        run: |
          import subprocess
          import os
          api = os.environ["API"]
          subprocess.run(f"python generate_vs2022_{api}.py")

      - name: Build
        shell: cmd
        run: '"%msbuild_path%\MSBuild.exe" /p:Platform=Windows /p:Configuration=Release /m spartan.sln'
        
      - name: Run engine
        shell: cmd
        run: |
          binaries/spartan_vulkan.exe -ci_test
          timeout /t 15

      - name: Check run results
        shell: pwsh
        run: |
          $file = "binaries/ci_test.txt"
          if (Test-Path $file) {
              $content = Get-Content $file
              if ($content -eq "0") {
                  Write-Output "Engine boot-up successful."
              } else {
                  Write-Error "Engine boot-up indicated a failure."
                  exit 1
              }
          } else {
              Write-Error "ci_test.txt not found. Engine boot-up failed."
              exit 1
          }

      - name: Create artifact
        if: github.event_name != 'pull_request' && matrix.api != 'd3d12'
        shell: cmd
        run: 'build_scripts\package_artifact.bat ${{ matrix.api }}'
      
      - name: Upload artifact
        if: github.event_name != 'pull_request' && matrix.api != 'd3d12'
        uses: actions/upload-artifact@v2
        with:
          name: build_${{ matrix.api }}
          path: build_${{ matrix.api }}.7z

  release:
    if: github.event_name != 'pull_request'
    runs-on: "ubuntu-latest"
    needs:
      - build
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
     
      - name: Download Vulkan build
        uses: actions/download-artifact@v2
        with:
          name: build_vulkan
          path: build_vulkan.7z
      
      - name: Publish release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            build_vulkan.7z
            LICENSE.txt
